### ISSUE TITLE
Recent games VOD behave as if watching the live stream after the game ending.

### ISSUE THREAD

**Issue by Aquassaut** [maxgalbu/xbmc.plugin.video.nba#30]
I tried watching a game from this week in the archive (VOD) with this extension (manually installed with branch `polling-service`, commit e0ea34f) and it seems to get the right game, but the video just shows "This game has ended", as if I was still watching the live stream long after the end of it.

I would appreciate it if you let me know how I can help with this issue.

Thank you for the hard work, it's appreciated.

**Comment by maxgalbu** [comment]
Which game?

**Comment by Aquassaut** [comment]
[OKC vs Philadelphia](https://watch.nba.com/game/20161026/OKCPHI) (game from 2016-10-26, tried to watch it on 2016-10-27 well after the end of the game)

**Comment by MumfordWiz** [comment]
Hey maxgalbu, 
First of all thanks for everything. the addon is great. I'm having the same issue as Aquassaut, after the games end, it takes a while until you can actually go and watch them from the beginning. It happened to all the games I tried to watch from last night, which finished 2-5 hours before.
It probably comes from the same issue as starting a game from the beginning even though it's in the middle. ( i haven't figured a way to do that). 
Thanks for all the help

**Comment by itzeddie** [comment]
There seems to be somewhere a 5000kbps bitrate available, I am seeing a number of the dodgy downloads online showing 5000kbps.

**Comment by besarbb** [comment]
maxgalbu, is there a way of fixing this "Game ended" screen that stays there for more than two hours after the game is over until it is actually available for us to watch it? I usually want to watch the games during the mornings just before going to school, but until now, all I can watch are the afternoon games.

It would be simply perfect if the game would be available as soon as it was so in nba.com.

Thanks so much for the add-on :)

**Comment by itzeddie** [comment]
I am seeing this again this evening, I can load the games fine on my phone but I only get the live feed which now shows game ended on Kodi.

**Comment by besarbb** [comment]
All these games are still not available from last night:
Spurs vs Clippers
Cavs vs Sixers
Kings vs Bucks
Thunder vs Wolves

I am checking the add-on like crazy, just like I am trying to not stumble upon spoilers :(

**Comment by maxgalbu** [comment]
Looks good to me now... Unfortunately I can't try to fix it if I don't have the issue

**Comment by besarbb** [comment]
There is Jazz vs Knicks right now with the same problem. This game should have actually only ended about 1-2 hours ago, but now it is in archive, and it won't play, with the screen being stuck at "GAME ENDED".

**Comment by itzeddie** [comment]
The Spurs vs. Rockets game from today (12th) is currently exhibiting this @maxgalbu if you want to have a look.

**Comment by maxgalbu** [comment]
I've checked this morning, and there were some games in that "condition", but I couldn't play them from the ipad (The selected game is not available). The ipad "method" of playing games (hls stream) is the one used in the plugin, because xbmc apparently doesn't support adaptive streams (or requires cookies in all the requests, I can't remember), which are used in the website flow (adaptive streams). I guess it's only possible from the adaptive stream, and not using HLS streams...

**Comment by Miss80** [comment]
@besarbb I've reported the same issue this weekend with the Celtics game in the kodi forum. 9.40 AM in the netherlands. You are not the only noisy person ;-)

**Comment by besarbb** [comment]
Is there something being done about this? It's 1:30pm in CET, and Clippers@Cavaliers is still not available to watch. :(

**Comment by besarbb** [comment]
Is it just me or there is not even one game playable from last night's games?

**Comment by salvatoreorange** [comment]
It's not just you.

**Comment by a7ypically** [comment]
@maxgalbu When a live game ends, before it is edited, you have to pass the starting time and duration to get the full stream when requesting the game URL. Otherwise you only get the end of stream which is the issue that is reported here.

in getGameUrl you need to add something like:

    if gs == 2 and not live_game:
        body['st'] = str(st)
        body['dur'] = str(et - st)

getGameUrl needs to receive the st and et parameters.
You can get them in addGamesLinks:

if not live and st,et in game:
 st = calendar.timegm(time.strptime(game['st'], '%Y-%m-%dT%H:%M:%S.%f')) * 1000
 et = calendar.timegm(time.strptime(game['et'], '%Y-%m-%dT%H:%M:%S.%f')) * 1000

Sorry, I don't have a code for you to pull, but with this changes in place in a similar code, it works for me.

**Comment by besarbb** [comment]
Hey @maxgalbu can we try what @a7ypically has suggested for the finals? I'd really appreciate that, as maybe I'll be able to watch the games unspoiled after I wake up... :)

**Comment by dav-sap** [comment]
Hey all, 
I did make a few changes that might work. I added the option to start from beginning while the game is still going. Problem is there are no games until the finals, I have no way to check if it works.
It does not change anything with the archive games, so the addon whatever I can check right now works. 
Any ideas for testing?

**Comment by a7ypically** [comment]
I don't think there's a way to test it.
I'm happy to review the code but I don't see a commit.

**Comment by dav-sap** [comment]
I don't have permissions for this git.
I started a new branch, but I can't add it as a remote branch.

**Comment by dav-sap** [comment]
created a pull request, check it out
https://github.com/maxgalbu/xbmc.plugin.video.nba/pull/52

**Comment by a7ypically** [comment]
Looks good to me and I think it should work. I added a comment about some safety checks you should probably add.
I did not check if you can play from the beginning while a game is live. Is that something LP allows on the web? I don't think I've seen this on mobile.

**Comment by dav-sap** [comment]
yea it works on the web and also on Android which i use, not sure regarding iPad, which the addon is based on. But I really don't know how the kodi will react to this, because it has no end time, it's why i need to run some tests. I'll try it out during the upcoming game. 
I'll take a look at the comments.

**Comment by dav-sap** [comment]
Tested & works!
You can start any game from the beginning.
While the game is still on you will be able to start it from the beginning, however the duration of the game will be from the beginning till the present time- meaning it probably won't continue live, so I'm still working on solutions for that. ( I have been thinking what will happen if we just use duration of like 4 hours, will it continue live? probably not need to be checked, any ideas will be welcomed)
Any game in the archive will now start from the beginning no matter what.
Any game in the LIVE section, you can choose to start from the beginning, so games that ended half an hour ago, and are still in the live section you'll be able to watch no problems.

https://github.com/maxgalbu/xbmc.plugin.video.nba/pull/52
