### ISSUE TITLE
Playback at 720p/60

### ISSUE THREAD

**Issue by premierpsp** [maxgalbu/xbmc.plugin.video.nba#93]
![untitled](https://user-images.githubusercontent.com/46852468/51432695-9a99aa00-1c1a-11e9-9bdc-4a6e14fc9696.png)
I can select 720p/ 60fps but it looks at 30fps. Does anyone else have this problem?

**Comment by ivankokan** [comment]
What do you exactly mean by "but it looks at 30fps"???

**Comment by premierpsp** [comment]
> What do you exactly mean by "but it looks at 30fps"???

Hi Ivan,
I mean, there's no difference between 30 or 60fps. when I select 60fps the video does not look smooth. It looks the same as with 30fps.

**Comment by ivankokan** [comment]
Hi, this is what I get:
![image](https://user-images.githubusercontent.com/1058211/51438865-0bd86c00-1cb2-11e9-92c3-364eb957bd56.png)
![image](https://user-images.githubusercontent.com/1058211/51438867-109d2000-1cb2-11e9-8b25-579a0503ff96.png)

It's hard for me to tell whether there is any difference in smoothness (I tried in a browser as well). What I can tell is that I experience lagging/buffering from time to time when I select higher quality.

If you have any doubts about the streams themselves, you should check https://github.com/peak3d/inputstream.adaptive, since this add-on relies on that one in stream processing.

**Comment by ivankokan** [comment]
@premierpsp Is this still valid?

**Comment by premierpsp** [comment]
> @premierpsp Is this still valid?

Nope, because NBA league pass from neulion doesn’t have support for 60fps.
Thanks!
